export default {
  "login": "ErgaAsDev",
  "id": 108246514,
  "node_id": "U_kgDOBnO18g",
  "avatar_url": "https://avatars.githubusercontent.com/u/108246514?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/ErgaAsDev",
  "html_url": "https://github.com/ErgaAsDev",
  "followers_url": "https://api.github.com/users/ErgaAsDev/followers",
  "following_url": "https://api.github.com/users/ErgaAsDev/following{/other_user}",
  "gists_url": "https://api.github.com/users/ErgaAsDev/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/ErgaAsDev/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/ErgaAsDev/subscriptions",
  "organizations_url": "https://api.github.com/users/ErgaAsDev/orgs",
  "repos_url": "https://api.github.com/users/ErgaAsDev/repos",
  "events_url": "https://api.github.com/users/ErgaAsDev/events{/privacy}",
  "received_events_url": "https://api.github.com/users/ErgaAsDev/received_events",
  "type": "User",
  "site_admin": false,
  "name": "ErgaAsDev",
  "company": null,
  "blog": "https://erga-personalweb.netlify.app/",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "Trying do some code here.",
  "twitter_username": null,
  "public_repos": 15,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2022-06-27T01:49:12Z",
  "updated_at": "2023-02-03T06:18:46Z"
}
